language: node_js
node_js:
  - "7"
cache:
  yarn: true
script:
    - npm rebuild node-sass
    - npm run build:pwa
    - npm run test-ci
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: develop